name: shift-education-user-service

services:
  postgres:
    image: postgres:17-alpine
    restart: on-failure
    ports:
      - "5432:5432"
    mem_limit: "256M"
    cpus: 1
    environment:
      POSTGRES_DB: user-service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql

  user-service:
    image: user-service:0.8
    restart: on-failure
    ports:
      - "8080-8090:8080"
    environment:
      POSTGRES_DB: user-service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./configs:/configs
    depends_on:
      - postgres
    deploy:
      mode: replicated
      replicas: 3

volumes:
  postgres_data:
